### ISSUE TITLE
[Research on] Python authentication codes for token-based authentication 

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#113]
- [ ] Go on google and look for code for token-based authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download for the programing languages you understand.
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by standardforever** [comment]
The code and the detail documentation of the code as been uploaded as Token_base_auth

**Comment by standardforever** [comment]
[auth_wiki_code.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9304679/auth_wiki_code.odt)
[project.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9304680/project.zip)
