### ISSUE TITLE
[Research on] PHP authentication codes for Password-based authentication 

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#114]
- [ ] Go on google and look for code for Password-based  authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download for the programing languages you understand.
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by davidemusi** [comment]
Here is JS code file for Password-based authentication
[JS_Password_Based_Auth.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9312183/JS_Password_Based_Auth.zip)

**Comment by standardforever** [comment]
These file contains PHP authentication codes, the zip files contains the code while the second file contains the documentation.
[PHP_auth_code_doc.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9308504/PHP_auth_code_doc.odt)
[php-user-authentication.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9308505/php-user-authentication.zip)
