### ISSUE TITLE
Custom error handling

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#12]
Add global custom error handling that returns errors with specific error messages and codes based on what type of error occurred on the server.

**Comment by Queen-Essyjay** [comment]
@Falence 
The assign yourself button is not visble.
<img width="1013" alt="Screenshot 2022-07-27 at 17 05 24" src="https://user-images.githubusercontent.com/105351236/181295496-57a41f3d-04aa-4ba2-942e-83ab75910b83.png">

**Comment by Falence** [comment]
Okay. That has been fixed.

**Comment by Falence** [comment]
PR: https://github.com/zuri-training/auth_wiki_team_10/pull/205
