### ISSUE TITLE
Navigation and footer component mobile design

### ISSUE THREAD

**Issue by AdaezeIkemefuna** [zuri-training/auth_wiki_team_10#142]

**Comment by 57YL35** [comment]
@AdaezeIkemefuna please, did we agree to justify or centralize the footer(contact us) etc?

**Comment by 57YL35** [comment]
Well done ada

**Comment by AdaezeIkemefuna** [comment]
Navigation responsiveness -AdaezeIkemefuna
Footer-Responsiveness - beatsbydan
