### ISSUE TITLE
Text Styles on Mobile screen

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#147]

**Comment by 57YL35** [comment]
Ok, that's done

**Comment by GabrielProsper** [comment]
Check this out @57YL35 @Madubuike4141 @Moyinolokungboye @ChiawaEmmanuel

**Comment by ChiawaEmmanuel** [comment]
The text styles are okay

**Comment by Moyinolokungboye** [comment]
Exactly what we agreed upon

**Comment by Madubuike4141** [comment]
They're okay.

**Comment by 57YL35** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1528%3A3063

Done
