### ISSUE TITLE
Sign up page mobile view wireframe

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#150]

**Comment by 57YL35** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=531%3A2596

Done

**Comment by GabrielProsper** [comment]
Completed 
[Figma link](https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=531%3A2596)
