### ISSUE TITLE
E-mail verification page mobile view wireframe

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#153]

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1527%3A2940
Please review.

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5703
I also did the hi - fi design. Please look at it.
