### ISSUE TITLE
Landing page mobile view  Hi-Fi

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#162]

**Comment by Bioluwatifee** [comment]
completed

**Comment by 57YL35** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1874%3A4466

Done

**Comment by Bioluwatifee** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5704
