### ISSUE TITLE
Documentation extended page mobile view  Hi-Fi

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#164]

**Comment by Madubuike4141** [comment]
We're done.

**Comment by izehaneefah** [comment]
Task completed kindly review
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5802

**Comment by Bioluwatifee** [comment]
adjusted the text sizes and element sizes

**Comment by 57YL35** [comment]
The text has been justified, kindly check

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5802
Done.
