### ISSUE TITLE
[Research on] Node js authentication codes for token-based authentication

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#197]
- [ ] Go on google and look for code for token-based authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download the code
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by standardforever** [comment]
Code and documentation for token base authentication
[jwt-project-for_js.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9310082/jwt-project-for_js.zip)
[token-based authentication-for_node.js.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9310084/token-based.authentication-for_node.js.odt)
