### ISSUE TITLE
[Research on] PHP authentication codes for token-based authentication

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#198]
- [ ] Go on google and look for code for token-based authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download the code
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by standardforever** [comment]
PHP documentation and auth code

[basic-php-jwt-auth.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9310155/basic-php-jwt-auth.zip)
[token-based authentication-for_PHP.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9310156/token-based.authentication-for_PHP.odt)
