### ISSUE TITLE
[Research on] Python authentication codes for Password-based authentication

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#199]
- [ ] Go on google and look for code for Password-based  authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download for the programing languages you understand.
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by standardforever** [comment]
Python auth code and documentation
[Password-based authentication -for_python.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9310617/Password-based.authentication.-for_python.odt)
[python-password-auth.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9310619/python-password-auth.zip)
