### ISSUE TITLE
[Research on] Node js authentication codes for Password-based authentication

### ISSUE THREAD

**Issue by Falence** [zuri-training/auth_wiki_team_10#200]
- [ ] Go on google and look for code for Password-based  authentication. You can check github too
- [ ] Understand how the different codes works, download and test it.
- [ ] Download for the programing languages you understand.
- [ ] When done, comment here, on this issue, and we'll have a call to see if it works

**Comment by standardforever** [comment]
Code for python auth and documentation

[node-js-password-auth.zip](https://github.com/zuri-training/auth_wiki_team_10/files/9310433/node-js-password-auth.zip)
[Password-based authentication-for_node_js.odt](https://github.com/zuri-training/auth_wiki_team_10/files/9310434/Password-based.authentication-for_node_js.odt)
