### ISSUE TITLE
mobile responsive design for all form pages

### ISSUE THREAD

**Issue by AdaezeIkemefuna** [zuri-training/auth_wiki_team_10#38]

**Comment by sanjayk0508** [comment]
hey, i want to work on this issue. I'm quite new to open source, may i know how can i run the site in local server (vscode). I cloned the code in vscode but don't know how run the site.

**Comment by AdaezeIkemefuna** [comment]
It's a team project and just members are allowed to do that. But if you want to learn more about open source and work on projects together, send me an email hamsaikemefuna@gmail.com
