### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#52]

**Comment by Moyinolokungboye** [comment]
User story complete. Kindly recheck for corrections. Thank you.
https://www.figma.com/file/S2PHA3zmeX0YrjdURVvc1T/User-Flow-and-Persona?node-id=256%3A182
https://www.figma.com/file/S2PHA3zmeX0YrjdURVvc1T/User-Flow-and-Persona?node-id=253%3A153

**Comment by izehaneefah** [comment]
Task completed. Kindly review 
https://www.figma.com/file/S2PHA3zmeX0YrjdURVvc1T/User-Flow-and-Persona?node-id=253%3A153
