### ISSUE TITLE
User flow

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#53]

**Comment by Madubuike4141** [comment]
I've completed this.

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/S2PHA3zmeX0YrjdURVvc1T/User-Flow-and-Persona?node-id=0%3A1
Please look at it.

**Comment by GabrielProsper** [comment]
Done
[Figma link](https://www.figma.com/file/S2PHA3zmeX0YrjdURVvc1T/User-Flow-and-Persona?node-id=0%3A1)
