### ISSUE TITLE
Color system

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#55]

**Comment by ChiawaEmmanuel** [comment]
Task Completed

**Comment by ChiawaEmmanuel** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=151%3A969

**Comment by Bioluwatifee** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=151%3A969
