### ISSUE TITLE
Button system

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#60]

**Comment by Madubuike4141** [comment]
Done.

**Comment by izehaneefah** [comment]
Completed
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=232%3A6977

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=232%3A6977
Check it out.
