### ISSUE TITLE
Illustrations 

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#63]

**Comment by GabrielProsper** [comment]
The previous illustration did not match with our work, correct it or change it.

**Comment by GabrielProsper** [comment]
The previous illustration did not match with our work, correct it or change it.

**Comment by GabrielProsper** [comment]
The previous illustration did not match with our work, correct it or change it.

**Comment by Bioluwatifee** [comment]
Illustrations were gotten from figma community and they now match our work. Done!
