### ISSUE TITLE
Documentation page wireframe

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#64]

**Comment by Madubuike4141** [comment]
Task completed.

**Comment by joseph-chibueze** [comment]
I'm done with it anything else.

**Comment by Aigoro** [comment]
Done with it ( https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1609%3A4420 )

**Comment by joseph-chibueze** [comment]
(https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1609%3A4420) Done.
