### ISSUE TITLE
Documentation page Hi-fi

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#75]

**Comment by izehaneefah** [comment]
Completed kindly review 
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1609%3A4765

**Comment by Moyinolokungboye** [comment]
done 
[https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1609%3A4764](url)
