### ISSUE TITLE
E-mail verification page Hi-fi

### ISSUE THREAD

**Issue by GabrielProsper** [zuri-training/auth_wiki_team_10#82]

**Comment by Madubuike4141** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5703
I'm done.

**Comment by Bioluwatifee** [comment]
https://www.figma.com/file/rim5Uin1lkaLl0JD5rhcf5/Zuri-Project-File?node-id=1852%3A5703
